default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres'%>
  password: <%= ENV['POSTGRES_PASSWD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_development

test:
  <<: *default
  database: auth_test

production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>
